 $(document).ready(function(){
$(".closebtn1").click(function(){
            $("#b1").slideUp("fast");
        })
        $(".closebtn2").click(function(){
            $("#b2").slideUp("fast");
        })
        $(".closebtn3").click(function(){
            $("#b3").slideUp("fast");
        })
        $(".closebtn4").click(function(){
            $("#b4").slideUp("fast");
        })
        $(".column1").click(function(){
            $("#b1").slideDown("fast");
            $(".skillText").slideUp("fast");
        })
        $(".column2").click(function(){
            $("#b2").slideDown("fast");
            $(".skillText").slideUp("fast");
        })
        $(".column3").click(function(){
            $("#b3").slideDown("fast");
            $(".skillText").slideUp("fast");
        })
        $(".column4").click(function(){
            $("#b4").slideDown("fast");
            $(".skillText").slideUp("fast");
        })
        
        $(".closebtn1").click(function(){
            $("#mB1").slideUp("fast");
        })
        $(".closebtn2").click(function(){
            $("#mB2").slideUp("fast");
        })
        $(".closebtn3").click(function(){
            $("#mB3").slideUp("fast");
        })
        $(".closebtn4").click(function(){
            $("#mB4").slideUp("fast");
        })
        $(".mColumn1").click(function(){
            $("#mB1").slideDown("fast");
        })
        $(".mColumn2").click(function(){
            $("#mB2").slideDown("fast");
        })
        $(".mColumn3").click(function(){
            $("#mB3").slideDown("fast");
        })
        $(".mColumn4").click(function(){
            $("#mB4").slideDown("fast");
        })
     })